version : '3'

services :
    nginx-server:
        restart : on-failure
        build: .
        ports:
            - "80:80"
        healthcheck:
            test: ["CMD", "wget", "-q", "-s", "http://localhost/"]    
        